<?php
/**
 * Created by PhpStorm.
 * User: Feliksas
 * Date: 22/09/2016
 * Time: 10:49
 */
namespace Tests\AppBundle\Entity;


use Tests\AppBundle\FixturesAwareWebTestCase;

class ImageRepositoryTest extends FixturesAwareWebTestCase
{
    private $em;

    public function testGetImages()
    {
        $this->em = static::$kernel->getContainer()->get('doctrine')->getManager();

        $images = $this->em->getRepository('AppBundle:Image')->getImages('created', 'desc')->getQuery()->getResult();
        $this->assertCount(1, $images);

    }
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->em->close();
        $this->em = null;
    }
}
