<?php
/**
 * Created by PhpStorm.
 * User: Feliksas
 * Date: 22/09/2016
 * Time: 12:06
 */

namespace Tests\AppBundle\Entity;
use Tests\AppBundle\FixturesAwareWebTestCase;
use AppBundle\Entity\Vote;
class VoteRepositoryTest extends FixturesAwareWebTestCase
{
    private $em;

    public function testCheckForVote()
    {
        $this->em = static::$kernel->getContainer()->get('doctrine')->getManager();

        $image = $this->em->getRepository('AppBundle:Image')->findOneBy(array('id' => 1));
        $user  = $this->em->getRepository('AppBundle:User')->findOneBy(array('id' => 2));
        $result = $this->em->getRepository('AppBundle:Vote')->checkForVote($user, $image);
        $this->assertTrue($result instanceof Vote);

    }
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->em->close();
        $this->em = null;
    }
}