services:
#    sandbox.example:
#        class: Sandbox\Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    security.access.image_voter:
        class:      AppBundle\Security\ImageVoter
        public:     false
        tags:
           - { name: security.voter }