languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "web/js/bootstrap.js"
- "app/app_dev.php"
- "app/check.php"
- "web/js/npm.js"
- "web/js/jquery*.js"
- "var/*"
- "vendor/*"
