language: php
php:
  - '5.6'
  - '7.0'
env:
  - SYMFONY_VERSION=3.1.*
before_install:
  - composer self-update
install:
  - composer install
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="92084407866b011b552bc80b60a3d50b803a6bb4bc4df05169c404f53c1d09e3" --format=php-clover coverage.clover
