# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_voter:
        class:      AppBundle\Security\ImageVoter
        public:     false
        tags:
           - { name: security.voter }
    sortable.twig.event_extension:
        class:      AppBundle\Twig\SortableExtension
        public:     false
        arguments: [ "@router", "@request_stack", "@twig" ]
        tags:
           - { name: twig.extension }
    web_login_authenticator:
        class: AppBundle\Security\WebLoginAuthenticator
        arguments: [ "@doctrine.orm.entity_manager", "@router", "@security.password_encoder", "@braincrafted_bootstrap.flash" ] 
        autowire: true
    api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: [ "@doctrine.orm.entity_manager" ] 
    test_login_authenticator:
        class: AppBundle\Security\TestLoginAuthenticator
        arguments: [ "@doctrine.orm.entity_manager", "@security.password_encoder" ]
    kernel.listener.user.created.event:
        class: AppBundle\EventListener\UserEventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: user.created.event, method: 'onUserCreatedAction' }
    kernel.listener.user.verification.event:
        class: AppBundle\EventListener\UserEventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: user.verification.event, method: 'onUserVerificationAction' }
    kernel.listener.image.delete.event:
        class: AppBundle\EventListener\ImageEventListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: image.delete.event, method: 'onImageDeleteAction' }
    kernel.listener.image.create.event:
        class: AppBundle\EventListener\ImageEventListener
        arguments: [ "@service_container"]
        tags:
            - { name: kernel.event_listener, event: image.create.event, method: 'onImageCreateAction' }
