# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_voter:
        class:      AppBundle\Security\ImageVoter
        public:     false
        tags:
           - { name: security.voter }
    sortable.twig.event_extension:
        class:      AppBundle\Twig\SortableExtension
        public:     false
        arguments: [ "@router", "@request_stack", "@twig" ]
        tags:
           - { name: twig.extension }
    web_login_authenticator:
        class: AppBundle\Security\WebLoginAuthenticator
        arguments: [ "@doctrine.orm.entity_manager", "@router", "@security.password_encoder", "@braincrafted_bootstrap.flash" ] 
        autowire: true
    api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: [ "@doctrine.orm.entity_manager" ] 
    test_login_authenticator:
        class: AppBundle\Security\TestLoginAuthenticator
        arguments: [ "@doctrine.orm.entity_manager", "@router", "@security.password_encoder", "@braincrafted_bootstrap.flash" ] 
