# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_voter:
        class:      AppBundle\Security\ImageVoter
        public:     false
        tags:
           - { name: security.voter }
    doctrine.image_listener:
        class: AppBundle\Doctrine\ImageListener
        arguments: []
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    doctrine.user_listener:
        class: AppBundle\Doctrine\UserListener
        arguments: ["@security.password_encoder", "@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }
    sortable.twig.event_extension:
        class: AppBundle\Twig\SortableExtension
        public: false
        arguments: [ "@router", "@request_stack" ]
        tags:
          - { name: twig.extension }
