_home:
    path:    /
    defaults:  { _controller: AppBundle:Default:index }
    methods:  [GET]
_about:
    path:    /about/
    defaults: { _controller: AppBundle:Default:about }
    methods:  [GET, POST]
_gallery:
    path:    /gallery/
    defaults: { _controller: AppBundle:Gallery:index }
    methods:  [GET]
_image:
    path:    /gallery/image/{id}
    defaults: { _controller: AppBundle:Gallery:Image }
    requirements:
        id: \d+
    methods:  [GET]
_image_vote:
    path:    /gallery/image/vote
    defaults: { _controller: AppBundle:Gallery:ImageVote }
    methods: [POST]
_image_edit:
    path:    /gallery/image/edit/{id}
    defaults: { _controller: AppBundle:Gallery:ImageEdit }
    requirements:
        id: \d+
    methods:  [POST]
_image_delete:
    path:    /gallery/image/delete/{id}
    defaults: { _controller: AppBundle:Gallery:ImageDelete }
    requirements:
        id: \d+
    methods:  [POST]
_upload:
    path:    /upload/
    defaults: { _controller: AppBundle:Gallery:upload }
    methods:  [GET, POST]
_registration:
    path:    /registration/
    defaults: { _controller: AppBundle:User:registration }
    methods:  [GET, POST]
_email_verification:
    path:    /verify/{confirmationToken}
    defaults: { _controller: AppBundle:User:emailVerification }
    methods: [GET, POST]
_user:
    path: /user/{userId}
    defaults: { _controller: AppBundle:User:index }
    requirements:
        slug: \d+
    methods:  [GET, POST]
_password_reset_request:
    path: /reset/
    defaults: { _controller: AppBundle:User:passwordResetRequest }
    requirements:
        slug: \d+
    methods:  [GET, POST]
_password_reset_verification:
    path: /reset/{confirmationToken}
    defaults: { _controller: AppBundle:User:passwordResetVerification }
    methods:  [GET, POST]
_api_demo:
    path: /rest/
    defaults: { _controller: AppBundle:Default:apiDemo }
    methods: [GET]
_api_gallery:
    path: /api/gallery/
    defaults: { _controller: AppBundle:Api:gallery, _format: json }
    methods: [GET]
_api_image:
    path: /api/image/{id}
    defaults: { _controller: AppBundle:Api:image, id: null, _format: json }
    methods: [GET]
_api_image_vote:
    path: /api/image/vote/
    defaults: { _controller: AppBundle:Api:imageVote, _format: json }
    methods: [POST]
_api_image_delete:
    path: /api/image/delete/{id}
    defaults: { _controller: AppBundle:Api:imageDelete, _format: json }
    methods: [DELETE]
login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods:  [GET, POST]
login_check:
    path: /login_check
    methods:  [GET, POST]
logout:
    pattern: /logout
    methods:  [GET, POST]
