services:
    security.access.image_voter:
        class:      AppBundle\Security\ImageVoter
        public:     false
        tags:
           - { name: security.voter }
    doctrine.user_listener:
        class: AppBundle\Doctrine\ImageListener
        arguments: []
        tags:
            - { name: doctrine.event_listener, event: prePersist }