AppBundle\Entity\Image:
    type: entity
    repositoryClass: AppBundle\Entity\ImageRepository
    table: images
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            length: 100
        resolution:
            type: string
            length: 100
        size:
            type: integer
        title:
            type: string
            length: 30
        description:
            type: string
            length: 250
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: images
            joinColumn:
                name: ownerId
                referencedColumnName: id
    oneToMany:
        votes:
            targetEntity: Vote
            mappedBy: image
            cascade: [ remove ]
